### ISSUE TITLE
调用encryptRsaParamWithPublicKey2ToBase64ToString时报错

### ISSUE THREAD

**Issue by Unicellular-SU** [guxiaonian/EncryptionInfo#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at android.util.Base64.encode(Base64.java:494)
        at fairy.easy.encryptioninformation.code.Base64Helper.encode(Base64Helper.java:102)
        at fairy.easy.encryptioninformation.asymmetry.AsymmetryHelper.encryptAsymmetryToBase64(AsymmetryHelper.java:113)
        at fairy.easy.encryptioninformation.asymmetry.AsymmetryHelper.encryptAsymmetryToBase64ToString(AsymmetryHelper.java:95)
        at fairy.easy.encryptioninformation.EncryptionHelper.encryptRsaParamWithPublicKey2ToBase64ToString(EncryptionHelper.java:168)

**Comment by guxiaonian** [comment]
@Unicellular-SU 感谢您的反馈，这边的Base64Helper中并没有对encode与decode的方法进行判空造成的。这边已经新版本处理了，再次感谢。
